name: Deploy Konnect Backend

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš€ SSHë¡œ ì„œë²„ ë°°í¬ ì‹¤í–‰
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VULTR_HOST }}
          username: root
          key: ${{ secrets.VULTR_SSH_KEY }}
          script: |
            cd /var/www/konnect-back
            git pull origin main
            npm ci
            npm run build
            pm2 restart konnect-api || pm2 start dist/main.js --name konnect-api
